source 'https://cdn.cocoapods.org/'

use_frameworks!

def common
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'
  pod 'RealmSwift', '~> 10.1'
end

target 'RxRealm_Example' do
  platform :ios, '9.0'
  common
  pod 'RxRealm', :path => '../'
end

target 'RxRealm_Tests' do
  platform :ios, '9.0'
  common
  pod 'RxBlocking', '~> 5.1'
  pod 'RxRealm', :path => '../'
end
